config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :photos, only: [:show, :new, :create] do
    resources :comments, only: :create
  end
  root to: 'photos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  
  mount_uploader :image, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy
  mount_uploader :profile_picture, ProfilePictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
  
    def create
      @photo = Photo.find(params[:photo_id])
      @comment = @photo.comments.build(comment_params)
      @comment.user = current_user
      if @comment.save
        redirect_to @photo, notice: 'Comentario agregado exitosamente'
      else
        redirect_to @photo, alert: 'No se pudo agregar el comentario'
      end
    end
  
    private
  
    def comment_params
      params.require(:comment).permit(:content)
    end
  end
  

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
  
    def show
      @photo = Photo.find(params[:id])
      @comments = @photo.comments
    end
  
    def index
        @photos = Photo.all
    end

    def new
      if current_user.email == 'karina@example.com' # Solo Karina puede subir fotos
        @photo = Photo.new
      else
        redirect_to root_path, alert: 'No tienes permiso para subir fotos'
      end
    end
  
    def create
      if current_user.email == 'karina@example.com'
        @photo = current_user.photos.build(photo_params)
        if @photo.save
          redirect_to @photo, notice: 'Foto subida exitosamente'
        else
          render :new
        end
      else
        redirect_to root_path, alert: 'No tienes permiso para subir fotos'
      end
    end
  
    private
  
    def photo_params
      params.require(:photo).permit(:title, :description, :image)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <strong><%= comment.author %>:</strong>
  <p><%= comment.body %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Kari Pic2" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/photos/index.html.erb
<h1>Galería de Fotos</h1>

<div class="photo-gallery">
  <% @photos.each do |photo| %>
    <div class="photo">
      <%= image_tag photo.image.url, alt: photo.title, class: "photo1" %>
      <h2><%= photo.title %></h2>
      <p><%= photo.description %></p>
      <%= link_to 'Ver foto', photo_path(photo) %>
    </div>
  <% end %>
</div>

app/views/photos/show.html.erb
<h1><%= @photo.title %></h1>
<p><%= @photo.description %></p>
<img src="<%= @photo.image.url %>" alt="<%= @photo.title %>" class="photo1">

<h2>Comentarios:</h2>
<%= render @comments %>

<%= form_with(model: [@photo, Comment.new], local: true) do |form| %>
  <div class="form-group">
    <%= form.label :content, "Agregar un comentario" %>
    <%= form.text_area :content %>
  </div>
  <%= form.submit "Comentar" %>
<% end %>